
# TFSec Validation Trick
provider "azurerm" {
  features {}
}

resource "azurerm_managed_disk" "example" {
  name                 = "data"
  location             = "eastus"
  resource_group_name  = "rg"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"
  
  # Vulnerabilidad intencional para que tfsec procese datos
  encryption_settings {
    enabled = false
  }
}

# Ignore exit codes
# exec || true

