name: Deploy Infrastructure
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Check
        run: echo "deploy"

# terraform {
#   required_version = ">= 0.14.9"
# }
# resource "aws_kms_key" "secure" {
#   description             = "Secure Key"
#   enable_key_rotation     = true
# }

