
# Action deployment definition requirement
# AWS KMS Key totalmente segura para pasar el escaneo sin errores

resource "aws_kms_key" "secure" {
  description             = "Secure KMS Key"
  deletion_window_in_days = 10
  enable_key_rotation     = true # Evita la vulnerabilidad AVD-AWS-0065
}

